In [21]:
import pandas as pd
import re


import nltk
from nltk.corpus import stopwords
nltk.download('stopwords') # If you just installed the package
set(stopwords.words('english'))

In [36]:
topics = 'C:/Users/uyent/PycharmProjects/crawler/coco_scrapy/codecombat.csv'
posts = 'C:/Users/uyent/PycharmProjects/crawler/coco_scrapy/post_codecombat.csv'

In [23]:
df_topics = pd.read_csv(topics)
df_topics

,id,title,created_at,last_posted_at,views,like_count,category_id
0,3575,Official Clan List,2015-04-17T00:52:28.189Z,2020-06-06T13:45:06.847Z,24526,277,9
1,4392,[Guide] Using the Boss Star,2015-07-04T02:44:33.376Z,2020-05-19T15:49:28.272Z,10397,54,6
2,15521,[Essentials] How To Post/Format Your Code Corr...,2018-08-12T22:34:04.021Z,2020-04-04T07:09:35.544Z,3077,8,9
3,19964,2019 Year Review,2020-01-08T07:02:15.627Z,2020-01-08T07:04:04.048Z,615,5,25
4,18174,Frequently Asked Questions,2019-04-17T08:07:46.471Z,2019-04-17T08:07:46.580Z,2125,3,4
...,...,...,...,...,...,...,...
6616,33,"Update docs on extra levels, inspector and deb...",2013-10-29T12:09:35.125Z,2013-10-30T16:47:54.804Z,1144,0,1
6617,8,Level: Hunter Triplets,2013-10-26T01:58:16.563Z,2013-10-30T16:41:32.097Z,2220,1,1
6618,4,Just set up this forum,2013-10-25T18:21:23.635Z,2013-10-26T20:24:57.943Z,1401,10,9
6619,3,Treema is ready,2013-08-28T23:01:03.650Z,2013-08-28T23:01:03.980Z,1454,1,3
6620,1,Discourse is awesome,2012-02-26T15:00:00.000Z,2012-02-26T15:00:00.000Z,953,9,9

In [37]:
df_posts = pd.read_csv(posts)
df_posts

,post_id,username,created_at,cooked,post_number,updated_at,reply_count,reply_to_post_num,reads,topic_id,user_id,topic_slug
0,88902,athian,2020-06-08T06:38:19.593Z,<p>Hey guys I’m in a hurry here I have more th...,1.0,2020-06-08T09:15:34.393Z,2.0,NaN,12,22098.0,11582.0,bookkeeper-help-me
1,88904,AnseDra,2020-06-08T06:47:33.808Z,"<aside class=""quote no-group"" data-username=""a...",2.0,2020-06-08T06:47:33.808Z,1.0,NaN,12,22098.0,11400.0,bookkeeper-help-me
2,88905,AnseDra,2020-06-08T06:49:33.583Z,"<p>Does it work now? <img src=""https://sjc3.di...",3.0,2020-06-08T06:49:33.583Z,0.0,2.0,12,22098.0,11400.0,bookkeeper-help-me
3,88906,AnseDra,2020-06-08T06:50:29.087Z,"<aside class=""quote no-group"" data-username=""a...",4.0,2020-06-09T07:48:13.249Z,1.0,NaN,11,22098.0,11400.0,bookkeeper-help-me
4,89038,athian,2020-06-09T06:43:46.638Z,"<p>Thanks <a class=""mention"" href=""/u/ansedra""...",5.0,2020-06-09T06:43:46.638Z,0.0,4.0,6,22098.0,11582.0,bookkeeper-help-me
...,...,...,...,...,...,...,...,...,...,...,...,...
43498,5221,marciofao,2014-12-17T20:49:04.185Z,<p>Why this piece of code does not work?</p>\n...,1.0,2014-12-17T20:50:48.606Z,0.0,NaN,23,1945.0,1375.0,siege-of-stonehold-js
43499,5223,sotonin,2014-12-17T20:53:37.417Z,<p>You are probably trying to pickup a flag wh...,2.0,2014-12-18T17:13:43.235Z,1.0,NaN,23,1945.0,1053.0,siege-of-stonehold-js
43500,5226,tjchan,2014-12-17T22:20:04.658Z,<p>Sotonin is right.</p>\n<p>You’ll want to:<b...,3.0,2014-12-17T22:20:04.658Z,0.0,2.0,20,1945.0,1374.0,siege-of-stonehold-js
43501,5264,marciofao,2014-12-18T02:15:18.734Z,"<p>Sotonin, You hint helped me pass the level,...",4.0,2014-12-18T02:15:18.734Z,0.0,NaN,17,1945.0,1375.0,siege-of-stonehold-js
43502,5295,nick,2014-12-18T16:55:10.698Z,"<p>Yup, we actually make the <code>pickUpFlag<...",5.0,2014-12-18T16:55:10.698Z,0.0,NaN,12,1945.0,1.0,siege-of-stonehold-js

In [38]:
df_posts = df_posts.fillna(0)
df_posts

,post_id,username,created_at,cooked,post_number,updated_at,reply_count,reply_to_post_num,reads,topic_id,user_id,topic_slug
0,88902,athian,2020-06-08T06:38:19.593Z,<p>Hey guys I’m in a hurry here I have more th...,1.0,2020-06-08T09:15:34.393Z,2.0,0.0,12,22098.0,11582.0,bookkeeper-help-me
1,88904,AnseDra,2020-06-08T06:47:33.808Z,"<aside class=""quote no-group"" data-username=""a...",2.0,2020-06-08T06:47:33.808Z,1.0,0.0,12,22098.0,11400.0,bookkeeper-help-me
2,88905,AnseDra,2020-06-08T06:49:33.583Z,"<p>Does it work now? <img src=""https://sjc3.di...",3.0,2020-06-08T06:49:33.583Z,0.0,2.0,12,22098.0,11400.0,bookkeeper-help-me
3,88906,AnseDra,2020-06-08T06:50:29.087Z,"<aside class=""quote no-group"" data-username=""a...",4.0,2020-06-09T07:48:13.249Z,1.0,0.0,11,22098.0,11400.0,bookkeeper-help-me
4,89038,athian,2020-06-09T06:43:46.638Z,"<p>Thanks <a class=""mention"" href=""/u/ansedra""...",5.0,2020-06-09T06:43:46.638Z,0.0,4.0,6,22098.0,11582.0,bookkeeper-help-me
...,...,...,...,...,...,...,...,...,...,...,...,...
43498,5221,marciofao,2014-12-17T20:49:04.185Z,<p>Why this piece of code does not work?</p>\n...,1.0,2014-12-17T20:50:48.606Z,0.0,0.0,23,1945.0,1375.0,siege-of-stonehold-js
43499,5223,sotonin,2014-12-17T20:53:37.417Z,<p>You are probably trying to pickup a flag wh...,2.0,2014-12-18T17:13:43.235Z,1.0,0.0,23,1945.0,1053.0,siege-of-stonehold-js
43500,5226,tjchan,2014-12-17T22:20:04.658Z,<p>Sotonin is right.</p>\n<p>You’ll want to:<b...,3.0,2014-12-17T22:20:04.658Z,0.0,2.0,20,1945.0,1374.0,siege-of-stonehold-js
43501,5264,marciofao,2014-12-18T02:15:18.734Z,"<p>Sotonin, You hint helped me pass the level,...",4.0,2014-12-18T02:15:18.734Z,0.0,0.0,17,1945.0,1375.0,siege-of-stonehold-js
43502,5295,nick,2014-12-18T16:55:10.698Z,"<p>Yup, we actually make the <code>pickUpFlag<...",5.0,2014-12-18T16:55:10.698Z,0.0,0.0,12,1945.0,1.0,siege-of-stonehold-js

In [39]:
import re
import warnings
warnings.filterwarnings("ignore")

for i in range(len(df_posts['cooked'])):
    clean = re.compile('<.*?>')
    df_posts['cooked'][i] = re.sub(clean, '', str(df_posts['cooked'][i]))
    df_posts['cooked'][i] = str(df_posts['cooked'][i]).replace('\n', '')

In [40]:
df_posts

,post_id,username,created_at,cooked,post_number,updated_at,reply_count,reply_to_post_num,reads,topic_id,user_id,topic_slug
0,88902,athian,2020-06-08T06:38:19.593Z,Hey guys I’m in a hurry here I have more thing...,1.0,2020-06-08T09:15:34.393Z,2.0,0.0,12,22098.0,11582.0,bookkeeper-help-me
1,88904,AnseDra,2020-06-08T06:47:33.808Z,athian:ifInstead of if put while athian:var i...,2.0,2020-06-08T06:47:33.808Z,1.0,0.0,12,22098.0,11400.0,bookkeeper-help-me
2,88905,AnseDra,2020-06-08T06:49:33.583Z,Does it work now?,3.0,2020-06-08T06:49:33.583Z,0.0,2.0,12,22098.0,11400.0,bookkeeper-help-me
3,88906,AnseDra,2020-06-08T06:50:29.087Z,athian:hero.say(hero.gold);Before this put on...,4.0,2020-06-09T07:48:13.249Z,1.0,0.0,11,22098.0,11400.0,bookkeeper-help-me
4,89038,athian,2020-06-09T06:43:46.638Z,Thanks @AnseDra ! It worked,5.0,2020-06-09T06:43:46.638Z,0.0,4.0,6,22098.0,11582.0,bookkeeper-help-me
...,...,...,...,...,...,...,...,...,...,...,...,...
43498,5221,marciofao,2014-12-17T20:49:04.185Z,Why this piece of code does not work?var flag ...,1.0,2014-12-17T20:50:48.606Z,0.0,0.0,23,1945.0,1375.0,siege-of-stonehold-js
43499,5223,sotonin,2014-12-17T20:53:37.417Z,You are probably trying to pickup a flag when ...,2.0,2014-12-18T17:13:43.235Z,1.0,0.0,23,1945.0,1053.0,siege-of-stonehold-js
43500,5226,tjchan,2014-12-17T22:20:04.658Z,Sotonin is right.You’ll want to:-Get the flag’...,3.0,2014-12-17T22:20:04.658Z,0.0,2.0,20,1945.0,1374.0,siege-of-stonehold-js
43501,5264,marciofao,2014-12-18T02:15:18.734Z,"Sotonin, You hint helped me pass the level, I’...",4.0,2014-12-18T02:15:18.734Z,0.0,0.0,17,1945.0,1375.0,siege-of-stonehold-js
43502,5295,nick,2014-12-18T16:55:10.698Z,"Yup, we actually make the pickUpFlag go to the...",5.0,2014-12-18T16:55:10.698Z,0.0,0.0,12,1945.0,1.0,siege-of-stonehold-js

In [28]:
# df_posts['topic_name'] = 'abc'

In [29]:
# topic_ids = df_posts['topic_id']
# top_ids = df_topics['id']
# for i in range(len(topic_ids)):
#     for j in range(len(df_topics['id'])):
#         if topic_ids[i] == top_ids[j]:
#             df_posts['topic_name'][i] = df_topics['title'][j]

In [42]:
df_posts.to_csv('posts_cc.csv', index=False, encoding='utf-8')

In [31]:
df_secured = df_posts

In [41]:
df_secured

,post_id,username,created_at,cooked,post_number,updated_at,reply_count,reply_to_post_num,reads,topic_id,user_id,topic_name
0,88609,athian,2020-06-06T12:52:58.494Z,you cn talk about anything here. Im just makin...,1,2020-06-06T23:55:56.724Z,0,0.0,12,22061,11582,Random stuff(Anything)
1,88611,athian,2020-06-06T12:55:28.727Z,this is just a test to see if the settings cha...,2,2020-06-06T12:55:28.727Z,0,0.0,12,22061,11582,Random stuff(Anything)
2,88664,EpicCoder999,2020-06-06T15:21:16.478Z,lets spamm then !!!,3,2020-06-06T15:21:16.478Z,1,0.0,10,22061,11533,Random stuff(Anything)
3,88665,EpicCoder999,2020-06-06T15:21:48.369Z,hi hi hi hi hihihihhihihi hello 20 charsdsdsd,4,2020-06-06T15:21:48.369Z,0,0.0,10,22061,11533,Random stuff(Anything)
4,88666,athian,2020-06-06T15:22:00.560Z,ok(20 characters!!!),5,2020-06-06T15:22:00.560Z,1,3.0,10,22061,11582,Random stuff(Anything)
...,...,...,...,...,...,...,...,...,...,...,...,...
43218,5144,BIGsmacjrMAC,2014-12-16T20:32:42.809Z,"Wow, thanks for the help guys. I didn’t know a...",14,2014-12-16T20:32:42.809Z,1,0.0,28,1752,1225,Can't use bash and attack in the same code
43219,5145,sotonin,2014-12-16T20:36:19.769Z,No problem.&amp;&amp; is an operator. it means...,15,2014-12-16T20:37:15.672Z,0,14.0,28,1752,1053,Can't use bash and attack in the same code
43220,4919,maredric,2014-12-14T22:11:15.208Z,"Hi,I experience strong instability mainly with...",1,2014-12-14T22:11:15.208Z,0,0.0,30,1890,1334,Codecombat repeated crash ( python version ) (...
43221,4945,BunchofCrooks,2014-12-14T23:33:16.701Z,"Hiya maredric,Have you tried another browser? ...",2,2014-12-14T23:33:16.701Z,0,0.0,29,1890,1187,Codecombat repeated crash ( python version ) (...
43222,5149,solar,2014-12-16T21:44:21.295Z,Can you post the code you are using?,3,2014-12-16T21:44:21.295Z,0,0.0,22,1890,1176,Codecombat repeated crash ( python version ) (...